# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyriPing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyriPing
  pod 'keyri-pod'

  target 'KeyriPingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyriPingUITests' do
    # Pods for testing
  end

end
